services:
  customers-db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=Local123
      - POSTGRES_USER=customers
      - POSTGRES_DB=customers
    ports:
      - "5432:5432"
  accounts-db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=Local123
      - POSTGRES_USER=accounts
      - POSTGRES_DB=accounts
    ports:
      - "5433:5432"
  ms-customers:
    build: ./ms-customers
    ports:
      - "8081:8080"
    depends_on:
      - customers-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customers-db:5432/customers
      JWT_SECRET: UH2yuJBa8XcycMm3L5DS7LRRd9yJbD430W9CUH+V1uI=
      ALLOWED_ORIGIN: http://ms-accounts:8080
      JWT_EXPIRATION: 900000
      SERVER_PORT: 8080
  ms-accounts:
    build: ./ms-accounts
    ports:
      - "8082:8080"
    depends_on:
      - accounts-db
      - ms-customers
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db:5432/accounts
      CUSTOMERS_SERVICE_URL: http://ms-customers:8080
      JWT_SECRET: UH2yuJBa8XcycMm3L5DS7LRRd9yJbD430W9CUH+V1uI=
      SERVER_PORT: 8080