server.port=8082

spring.application.name=ms-accounts
spring.datasource.url=jdbc:postgresql://localhost:5433/accounts
spring.datasource.username=accounts
spring.datasource.password=Local123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.expiration=86400000
jwt.secret=UH2yuJBa8XcycMm3L5DS7LRRd9yJbD430W9CUH+V1uI=

customers.service.url=localhost:8081
management.endpoints.web.exposure.include=health
bank.daily-withdrawal-limit=1000