server.port=8082

spring.application.name=ms-accounts
spring.datasource.url=jdbc:postgresql://localhost:5433/accounts
spring.datasource.username=accounts
spring.datasource.password=Local123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.expiration=86400000
jwt.secret=9pST5kS3k1SzVLb3G+eaQxgpTOpDgXqKOV653IirwBk=

customers.service.url=localhost:8081