server.port=8081

spring.application.name=ms-customers
spring.datasource.url=jdbc:postgresql://localhost:5432/customers
spring.datasource.username=customers
spring.datasource.password=Local123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.expiration=86400000
jwt.secret=kOnVtkVdMLAJCb4R3rcLzVRhXUvav19rPXsxFl2ztD0=