spring.application.name=ms-customers
spring.datasource.url=jdbc:postgresql://localhost:5432/customers
spring.datasource.user=customers
spring.datasource.password=Local123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect